nelmio_api_doc:
    documentation:
        info:
            title: CopyPatrol
            description: A tool that allows you to see recent Wikipedia edits that are flagged as possible copyright violations.
            version: 1.0.0
        components:
            parameters:
                lang:
                    name: lang
                    in: path
                    required: true
                    description: The language of the project
                    schema:
                        type: string
                        example: en
            schemas:
                Case:
                    type: object
                    description: A case of a possible copyright violation
                    properties:
                        submission_id:
                            type: integer
                            description: The UUID of the submission in the iThenticate database
                            example: 123e4567-e89b-12d3-a456-426614174000
                        sources:
                            type: array
                            description: The sources associated with the case
                            items:
                                type: object
                                $ref: '#/components/schemas/Source'
                        page_title:
                            type: string
                            description: The full title of the page
                            example: Draft:Foo bar
                        page_dead:
                            type: boolean
                            description: Whether the page has been deleted
                            example: false
                        new_page:
                            type: boolean
                            description: Whether the page is new as of this edit
                            example: false
                        diff_id:
                            type: integer
                            description: The ID of the record in the CopyPatrol database
                            example: 123456
                        diff_timestamp:
                            type: string
                            format: date-time
                            description: The timestamp of the edit
                            example: 2021-01-23 12:59
                        diff_size:
                            type: integer
                            description: The size of the edit
                            example: -250
                        summary:
                            type: string
                            description: The edit summary
                            example: /* Example summary */
                        tags:
                            type: array
                            description: The tags associated with the edit
                            items:
                                type: string
                                example: [ "mobile edit", "mobile app" ]
                        wiki_projects:
                            type: array
                            description: The WikiProjects associated with the page
                            items:
                                type: string
                                example: [ "Philosophy", "Science" ]
                        rev_id:
                            type: integer
                            description: The revision ID of the edit
                            example: 123456789
                        rev_parent_id:
                            type: integer
                            description: The parent revision ID of the edit. `0` for new pages
                            example: 0
                        editor:
                            type: string
                            description: The username of the editor
                            example: Example user
                        edit_count:
                            type: integer
                            description: The edit count of the editor
                            example: 123
                        status:
                            type: integer
                            description:
                                The status of the case.
                                - `0` for unreviewed
                                - `1` for fixed
                                - `2` for no action needed
                        status_user:
                            type: string|null
                            description: The username of the user who last changed the status
                            example: Example User
                        status_timestamp:
                            type: string
                            format: date-time
                            description: The timestamp of the last status change
                            example: 2021-01-23 12:59
                        project:
                            type: string
                            description: The domain of the project
                            example: en.wikipedia.org
                Source:
                    type: object
                    description: A source of a possible copyright violation
                    properties:
                        source_id:
                            type: integer
                            description: The ID of the source in the CopyPatrol database
                            example: 123456
                        description:
                            type: string
                            description: The description of the URL (FIXME)
                        url:
                            type: string
                            description: The URL of the source
                            example: https://example.org
                        percent:
                            type: number
                            format: float
                            description: The similarity percentage of the diff against the source
                            example: 99.99

            responses:
                404:
                    description: Not found
                500:
                    description: Internal server error

    areas: # to filter documented areas
        path_patterns:
            - ^/api(\.json$|\/)
