toolforge:
    intuition:
        domain: 'copypatrol'

    oauth:
        url: '%env(OAUTH_URL)%'
        consumer_key: '%env(OAUTH_KEY)%'
        consumer_secret: '%env(OAUTH_SECRET)%'
        logged_in_user: '%env(LOGGED_IN_USER)%'
