version: '3.8'

# =========================================================
#
# This file allows anyone to start the CopyPatrol web interface
# locally. Additional configuration on the `.env` file is still
# required to bring this up.
#
# Ensure the following before bringing this file up (in order):
#  - CopyPatrol image must be built.
#    - Use `docker-compose -f docker-compose.dev.yml build` to build the image.
#  - Composer packages must be installed
#    - Use `docker run --rm -it -v $(pwd):/app wikimedia/copypatrol composer install` to install packages.
#  - `.env` contains appropriate credentials
#    - `OAUTH_CONSUMER_TOKEN` and `OAUTH_SECRET_TOKEN` must be supplied
#    - SQL usernames and passwords must be supplied
#    - `DB_HOST` and `DB_REPLICA_HOST` must be `host.docker.internal`
#  - Replica SQL DB must be accessible through port 4711 on the host (see README)
#  - Tool SQL DB must be accessible through port 4712 on the host (see README)
#
# =========================================================

volumes:
    redis:

services:
    copypatrol:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        image: wikimedia/copypatrol-development
        depends_on:
            -   copypatrol-redis
        links:
            - "copypatrol-redis:tools-redis"
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - "80:80"
        volumes:
            # This will bind the files in the development directory to the app.
            -   type: bind
                source: "."
                target: "/app"
                read_only: true
            # Cache directory should not be read-only
            -   type: bind
                source: "./cache"
                target: "/app/cache"
        restart: always
        stop_grace_period: 1m
    copypatrol-redis:
        image: redis:alpine
        volumes:
            -   redis:/data
        restart: always
        stop_grace_period: 1m
